nodes:
  - address: "{{ host_ip }}" # 离线环境节点 IP
    hostname_override: "{{ ansible_hostname }}"
    user: "{{ rke_user }}"
    role: ["controlplane", "etcd"]
    ssh_key_path: /root/.ssh/id_rsa
  - address: 172.22.150.27 # 离线环境节点 IP
    user: apps
    role: ["worker"]
    ssh_key_path: /root/.ssh/id_rsa
upgrade_strategy:
  max_unavailable_worker: 50%
  max_unavailable_controlplane: 1
  drain: false
ignore_docker_version: true
private_registries:
  - url: mirrors.com:80 # 私有镜像库地址
    user: admin
    password: "U59mzstk#kaeyC_N"
    is_default: true
#kubernetes_version: "v1.23.16-rancher2-3"
kubernetes_version: "v1.21.14-rancher1-1"
network:
   plugin: calico
services:
    etcd:
      snapshot: true
      creation: 6h
      retention: 24h
    kube-api:
      extra_args:
        # Enable audit log to stdout
        enable-admission-plugins: "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,NodeRestriction,Priority,TaintNodesByCondition,PersistentVolumeClaimResize,PodNodeSelector"
#        enable-admission-plugins: "NamespaceLifecycle,PodNodeSelector"
    kubelet:
      extra_args:
        cpu-manager-policy: "static"
        reserved-cpus: 0-3

authentication:
  strategy: x509
  sans:
    - "172.22.150.22"
    - "172.22.150.23"
    - "172.22.150.24"
    - "172.22.150.25"
    - "172.22.150.26"
    - "172.22.150.27"
    - "172.22.150.250"
