---
# defaults file for roles/init-os
install_pkg:
  - telnet
  - expect
  - rsync
  - nc
  - nfs-utils
  - net-tools
  - python-docker-py
  - python-devel
  - chrony
  - wget

chrony_server: "{{ deploy_node_ip }}"
arch:
  x86_64:
    base: 'CentOS-Base.repo'
  arm64:
    base: 'CentOS-altarch-7.repo'

deploy_node_ip: "{{ groups['k8s-master'][0] }}"
