---
- name: install docker-ce 
  yum:
    name: "docker-ce-{{ docker_version }}"
    state: present

- name: create docker directory /etc/docker
  file:
    path: /etc/docker
    state: directory

- name: Copy Docker Daemon
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: started docker service
  systemd:
    name: docker
    state: restarted
    enabled: yes

