---
# tasks file for roles/rke
- name: Install ipvsadm
  yum:
    name: ipvsadm
    state: present
  when: kube_proxy_mode == 'ipvs'

- name: Load ip_vs core module
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh

- name: Copy ipvs module configuration to /etc/modules-load.d/
  copy:
    content: |  
      ip_vs  
      ip_vs_rr  
      ip_vs_wrr  
      ip_vs_sh
    dest: /etc/modules-load.d/ipvs.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - update initramfs

- name: create rke user
  user:
    name: "{{ rke_user }}"
    shell: /bin/bash
    group: docker

- name: Create Directory .ssh
  file:
    path: "/home/{{ rke_user }}/.ssh"
    mode: 0700
    owner: apps
    group: docker
    state: directory

- name: Copy SSH public key for root
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.ssh/{{ item }}"
  with_items:
    - authorized_keys
    - id_rsa
    - id_rsa.pub
  delegate_to: "{{ groups['k8s-master'][0] }}"
  run_once: true

- name: Copy SSH public key for {{ rke_user }}
  copy:
    src: "{{ item }}"
    dest: "/home/{{ rke_user }}/.ssh/{{ item }}"
    group: docker
  with_items:
    - authorized_keys
    - id_rsa
    - id_rsa.pub

- name: Check RKE is Exist
  stat:
    path: /usr/local/bin/rke
  register: rke_status
  delegate_to: "{{ groups['k8s-master'][0] }}"
  run_once: true

- name: Check Kubectl is Exist
  stat:
    path: /usr/local/bin/kubectl
  register: kubectl_status

- name: Debug RKE Status
  debug:
    msg: "{{ rke_status.stat.exists }}"

- name: Debug Kubectl Status
  debug:
    msg: "{{ kubectl_status.stat.exists }}"

- name: Download RKE binary
  get_url:
    url: "https://github.com/rancher/rke/releases/download/{{ rke_version }}/rke_linux-amd64"
    dest: "/usr/local/bin/rke"
    mode: "0777"
    force: true
  register: rke_download_result
  until: rke_download_result.status_code == 200
  retries: 5
  delay: 3
  when: not rke_status.stat.exists
  delegate_to: "{{ groups['k8s-master'][0] }}"
  run_once: true

- name: debug rke_download_result
  debug:
    msg: "{{ rke_download_result }}"

- name: Download Kubectl binary
  get_url:
    url: "https://dl.k8s.io/release/v1.21.14/bin/linux/amd64/kubectl"
    dest: "/usr/local/bin/kubectl"
    mode: "0777"
    force: true
    validate_certs: no
  when: not kubectl_status.stat.exists

- name: Copy cluster.yml
  template:
    src: cluster.yml.j2
    dest: /root/cluster.yml
  delegate_to: "{{ groups['k8s-master'][0] }}"
  run_once: true

- block:
  - name: RKE Generating images
    shell: "rke config --system-images --version {{ k8s_version }}|grep -v 'Generating images'|grep -v 'noiro'"
    register: rke_image

  - name: Add rancher/rke-tools:v0.1.88 to the output list
    set_fact:
      updated_rke_images: "{{ rke_image.stdout_lines + ['rancher/rke-tools:v0.1.88'] }}"

#  - name: DownLoad RKE Image
#    docker_image:
#      name: rancher/rke-tools:v0.1.88
#      source: pull
#      state: present
#
#  - name: Build Tag From RKE Image
#    docker_image:
#      name: "{{ item }}"
#      repository: "{{ deploy_node_ip }}:5000/{{ item }}"
#      source: local
#      push: yes
#    with_items:
#      - rancher/rke-tools:v0.1.88

#  - name: Upload RKE Image
#    docker_image:
#      name: rancher/rke-tools:v0.1.88
#      repository: "{{ deploy_node_ip }}:5000/rancher/rke-tools:v0.1.88"
#      source: local
#      push: yes

  - name: Download RKE system image
    docker_image:
      name: "{{ item }}"
      source: pull
      state: present
    with_items: "{{ updated_rke_images }}"

  - name: Build Tag From RKE Image
    docker_image:
      name: "{{ item }}"
      repository: "{{ deploy_node_ip }}:5000/{{ item }}"
      source: local
      push: yes
    with_items: "{{ updated_rke_images }}"

  when: ansible_host == deploy_node_ip

- name: Startup K8S
  shell: rke up >> /root/rke_up.log 2>&1
  delegate_to: "{{ groups['k8s-master'][0] }}"
  run_once: true

- name: Create Directory /root/.kube
  file:
    path: /root/.kube
    state: directory

- name: Fetch kube_config_cluster.yml to /root/.kube/config
  fetch:
    src: /root/kube_config_cluster.yml
    dest: /root/.kube/config
    flat: yes
  delegate_to: "{{ groups['k8s-master'][0] }}"
  run_once: true

- name: Copy /root/.kube/config
  copy:
    src: /root/.kube/config
    dest: /root/.kube/config

- name: Set vip to .kube/config
  lineinfile:
    path: /root/.kube/config
    regexp: '^server: "https://.*:6443"$'
    line: 'server: "https://{{ keepalived_vip }}:6443"'